### PR TITLE
Composer autoloads Charcoal + Config out of public root

### PR DESCRIPTION
**Pull request by mcaskill**
This PR does a few things:

- **Moved `config/` directory up; out of public root.** The reason we started using the `www/` directory was to move the configuration files out of the public reach.
- **Renamed `config.local.json` to `config.example.json`.** Eliminates the risk of accidentally pulling in another developer's local environment settings. It's purpose has always been to serve as a _sample_.
- **Improved application configuration.**
  - Cleaned up `config.json`,
  - Added `"default_template": "404"` and `"default_template_controller": "Boilerplate_Template_Controller"`,
  - The "display_errors" setting is now dependant on `"debug": { "active": true }`,
  - The project URL will automagically attempt to resolve if not provided with `"project_url": "[[:host]]/foobar"` (see `config.php` for replacement tokens).
- **Improved Boilerplate initialization.** Default options handled intelligently from the initialization process.
- **Using only one index controller.** Removed `www/charcoal.php` and updated `.htaccess`.
- **Cleaned up Composer manifest.**

### CODE REVIEW

**Comment by stephenbe** [comment]
Perfect, thank you @mcaskill

**Comment by mcaskill** [comment]
> The project URL will automagically attempt to resolve if not provided with "project_url": "[[:host]]/foobar" (see config.php for replacement tokens).

For discussion upon @mducharme's return, maybe moving that portion to [`charcoal-legacy`](//github.com/locomotivemtl/charcoal-legacy)

**Comment by stephenbe** [comment]
Any update on this?

**Comment by stephenbe** [comment]
@mcaskill I see you fixed the issues good to see, thanks
@mducharme Est-ce qu'on peut merge ce PR svp?

**Pull request closed without merging**
