### PR TITLE
Simpler grid, better headings, some tools, clean stuff

### PR DESCRIPTION
**Pull request by AntoineBoulanger**

### CODE REVIEW

**Comment by mcaskill** [comment]
Cold blooded! I'd suggest we keep @stephenbe in the package for historical purposes or move him to a _contributors_ section.

**Comment by dominiclord** [comment]
:+1:

**Comment by AntoineBoulanger** [comment]
Historical purposes haha. He is still in https://github.com/locomotivemtl/locomotive-boilerplate/graphs/contributors and he won't use this email anymore so I don't think it's super usefull. BTW you can add yourself in. Or maybe I can just remove myself, it's pretty useless at this point.

**Comment by mcaskill** [comment]
I misread the changeset. you two were already members of _contributors_. I'd remove it entirely, then.

I would also leave any attributions in place, such as the comment left for `@mixin clearfix`. It's polite to cite your sources at least somewhere (maybe the README).

**Comment by mcaskill** [comment]
Otherwise :+1:

**Pull request merged**
