### PR TITLE
Refactored Sass

### PR DESCRIPTION
**Pull request by mcaskill**
Merged changes and features to SCSS from various recent projects and implemented some of the latest features from InuitCSS.

When using the SCSS structure in your own project, modify the `settings/config*.scss` files and leave `settings/core.scss` intact.

Changes:
- Updated Normalize to 5.0.0;
- Migrated imports to `main.scss`;
- Split `settings.scss` into smaller parts;
- Revised variable names for settings;
- Added spacing unit variables;
- Replaced `objects/grid.scss` with `objects/layout.scss` (from inuitcss);
- Added `objects/crop.scss` and `objects/ratio.scss` (from inuitcss);
- Added @font-face mixin/function from Bourbon;
- Added various new functions and mixins (widths, font-size, truncation,…);
- Renamed Trumps to Utilities;
- Added vatious new Utilities (print, states, spacing, widths);
- Reorganized Utilities into topics;

Notes:
- Renamed the `.o-grid` object to `.o-layout` for explicitness.  
  > The problem with `.grid` is that it implies grid systems/page-level layout, whereas `.layout` implies that you can lay _anything_ out. Which you can :)

  — [Harry Roberts](/inuitcss/objects.layout/issues/3#issuecomment-45723902)
- Added `.o-crop` and `.o-ratio` objects from inuitcss. These are simpler versions of the `tools/ratio.scss` tool.

### CODE REVIEW

**Comment by dominiclord** [comment]
So,  `o-btn` and `o-button`. Might be a bit confusing, no?

**Comment by dominiclord** [comment]
I'd avoid using classes that don't fall under the namespacing conventions, such as `.is-hidden`, `.is-invisible` and `.is-visible`. My opinion is that these should be prefixed with `u-`.

This is also confusing because of the existence of `.u-hidden` which doesn't extend the `@u-hidden` mixin. I suggest renaming `.is-hidden` to `.u-hidden`.

My main reasoning for this is that we usually use the `.is-*` formulations for JS added classes. Having these `.is-*` classes in the core styles prevents us from using these very generic class names in JS interactions/animations/toggles.

**Comment by mcaskill** [comment]
@dominiclord Hrm. Indeed! That is a typo leftover from copy pasting from project to project.

Should we use `btn` and `button`? I like the former because its shorter.

**Comment by mcaskill** [comment]
> I'd avoid using classes that don't fall under the namespacing conventions, such as `.is-hidden`, `.is-invisible` and `.is-visible`. My opinion is that these should be prefixed with `u-`.

> This is also confusing because of the existence of `.u-hidden` which doesn't extend the `@u-hidden` mixin. I suggest renaming `.is-hidden` to `.u-hidden`.

> My main reasoning for this is that we usually use the `.is-*` formulations for JS added classes. Having these `.is-*` classes in the core styles prevents us from using these very generic class names in JS interactions/animations/toggles.

We can remove the `.u-hidden`, it was there to complement to other `display` utility classes.

As for the styles declared for the `.is-*`, those should remain in the core as a starting point. I see too often people using _visibile_ and _invisible_ for non-visibility/opacity purposes.

**Comment by dominiclord** [comment]
I agree that we need them in the core. However, I think they should be prefixed, like the rest of the _utilities_ classes.

**Comment by mcaskill** [comment]
I've removed `.u-hidden` because of its apparent confusion.

There are many similarities between, but I see the namespaces as such:
- `.-*` (_modifier_ class) — object / component-specific permanent rules
- `.u-*` (_utility_ class) — generic permanent rules
- `.is-*`, `.has-*` (_state_ style) — generic temporary rules
- `.js-*` — has a JS binding or behaviour affecting it

```html
<article class="c-modal  -wide  is-open" tabindex="-1" role="dialog" data-module="Modal Changeset">
  <div class="c-modal_dialog" role="document">
    <header class="c-modal_header">
      <h2 class="o-h1  u-truncate">Apply Changes?</h2>
      <button type="button" class="close js-dismiss" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </header>
    <div class="c-modal__body">
      […]
    </div>
    <footer class="c-modal_footer">
      <p class="o-layout">
        <span class="o-layout__item  u-1/3">
          <a href="" class="c-btn  -negative  js-dismiss">Cancel</a>
        </span>
        <span class="u-screen-reader-text">or</span>
        <span class="o-layout__item  u-2/3">
          <a href="" class="c-btn  -positive  js-accept">Apply</a>
        </span>
      </p>
    </footer>
  </div>
</article>
```

— [More Transparent UI Code with Namespaces](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#the-namespaces)

**Comment by mcaskill** [comment]
Speaking of `.js-*`, I often think we should bind behaviour to data attributes. Using the example above:

```html
<article class="c-modal  -wide  is-open" data-module="Modal Changeset">
  <button type="button" class="close" data-dismiss="modal changeset">[…]</button>
  <a href="" class="c-btn  -negative" data-dismiss="modal changeset">Cancel</a>
  <a href="" class="c-btn  -positivet" data-apply="changeset" data-dismiss="modal">Apply</a>
</article>
```

**Comment by AntoineBoulanger** [comment]
Since it's a boilerplate, there are some things I would remove we don't want to be deleting a lot of stuff every time we start a projet, it should be the bare miminum and you add stuff on top of it.

`_core.scss`: Why is this necessary?
`_core.animations`: Weird file name.
`_config.scss`: Unnecessary fonts vars, just 1 variable with sans-serif in it will do. `$global-` prefix on variables seems unnecessary to me too, it just longer for nothing, you understand that `$font-size` is global.
`_config.colors.scss`: I would just keep black and white for in `Palette`. Specific vars are too specific, i would remove `highlighted`, `deleted`, `inserted`
`_config.aliases.scss`: I don't understand why these are in this file, move them in `config.scss`.
`_layout.scss`: Not sure about the name change, we are used to `.o-grid` at this point, it's shorter and it's just fine.
`_button.scss`: I think that's it's weird that it's the only class with an abbreviation `o-btn`. We were using the full `o-button` before for consistency with everything else. You like that this is shorter but everything else is now longer... (variables, layout, etc).
`headings.scss`: Shouldn't we keep the heading variables in the config file? I would keep the heading line-height too since it's often different.

That's what I see right, now. Thanks.

**Pull request merged**
