### PR TITLE
ES6 merge with master (without charcoal)

### PR DESCRIPTION
**Pull request by quentinhocde**
- Convert es5 to es6
- Disable eslint pour les vendors
- Disable browserify pour les vendors
- update de la task watch avec 2 watchs : javascript_app & javascript_vendors

### CODE REVIEW

**Comment by dominiclord** [comment]
I added a few changes that I was testing in a new project. See [3506a95](https://github.com/locomotivemtl/locomotive-boilerplate/commit/3506a95ee90846c6c239f6d92f7452e7d69dd50d).

**Comment by AntoineBoulanger** [comment]
What is the status of this?

**Comment by dominiclord** [comment]
I'd go for it. Nothing stopping news features from being added later on.

**Comment by AntoineBoulanger** [comment]
Say no more.

**Pull request merged**
