### PR TITLE
External grunt tasks

### PR DESCRIPTION
**Pull request by stephenbe**
* all the grunt tasks are now external
* changed package.json name from project-x to boilerplate
* removed imagemin task(we now use kraken)
* add load-grunt-tasks
* fixed a few indent issues with various grunt tasks

### CODE REVIEW

**Comment by stephenbe** [comment]
https://github.com/locomotivemtl/locomotive-boilerplate/issues/7

**Comment by AntoineBoulanger** [comment]
You don't have to write every require by hand, you can use something like:
```

**Comment by AntoineBoulanger** [comment]
You don't have to write every require by hand, you can use something like:
```
function loadConfig(path) {
    var glob = require('glob');
    var object = {};
    var key;

    glob.sync('*', {cwd: path}).forEach(function(option) {
      key = option.replace(/\.js$/,'');
      object[key] = require(path + option);
    });

    return object;
  }
```

**Comment by AntoineBoulanger** [comment]
Or this plugin: https://github.com/firstandthird/load-grunt-config, but i never tried it

**Comment by stephenbe** [comment]
@AntoineBoulanger I just committed that change, thank you!

**Comment by AntoineBoulanger** [comment]
:thumbsup:

**Comment by mducharme** [comment]
phplint *is* used.

**Comment by stephenbe** [comment]
I assumed no one ever used it because right now the task is not properly configured. The paths are wrong.

**Comment by stephenbe** [comment]
@mducharme Just added back the linting for json and php!

**Pull request merged**
